name: campus_store
description: A digital marketplace for students to buy, sell, and exchange goods and services.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  paystack_payment: ^0.0.4

  # Firebase
  firebase_core: ^2.18.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.3.1
  firebase_app_check: ^0.2.1+3
  fl_chart: ^0.68.0

  # Image picker
  image_picker: ^1.0.4

  # UI & Navigation
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.1
  get:
  get_storage:

  # Utilities
  intl: ^0.19.0
  uuid: ^4.1.0
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # Splash screen plugin
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#f27a1c"
  image: assets/icons/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  remove_alpha_ios: true

  android_12:
    color: "#f27a1c"
    image: assets/images/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700